# Generated by Django 2.2.3 on 2019-08-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontact',
            name='cat',
            field=models.CharField(default=' ', max_length=238),
        ),
        migrations.AddField(
            model_name='pagecontact',
            name='sub',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
